### ISSUE TITLE
Variable not in scope: (<>) :: Parser String -> Mod f2 a2 -> t1

### ISSUE THREAD

**Issue by p-alik** [pbrisbin/heroku-build#1]
First of all thanks for your [blog](https://robots.thoughtbot.com/applicative-options-parsing-in-haskell).
My attempt to build [Options.hs](
https://github.com/pbrisbin/heroku-build/blob/master/src/HerokuBuild/Options.hs) ends in exception:
```
Options.hs:27:15: error:
    • Variable not in scope: (<>) :: Parser String -> Mod f2 a2 -> t1
    • Perhaps you meant one of these:
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘>>’ (imported from Prelude)
```
`import Data.Semigroup ((<>))` solves the issue

**Comment by pbrisbin** [comment]
Thanks for the report, might be a change in versions somewhere. I'll take a look tonight.

**Comment by pbrisbin** [comment]
Should be fixed now. Thanks!
